@startuml
!theme blueprint
participant "Consumer" as consumer
participant "Web Site" as website
participant "EasyCard Checkout" as checkout
participant "EasyCard API" as api

consumer->website: start payment
website->api: //[[MetadataApi.md#create-consumer-record create Consumer]]// record
api-->website: Created <b>ConsumerID</b>
website->api: //[[TransactionsApi.md#create-payment-link-to-checkout-page create Payment Intent]]// with Amount=0
api-->website: <b>Payment Intent</b> url
website->checkout : open <b>Payment Intent</b> url
consumer->checkout : fill credit card details to save in EasyCard
checkout->website: redirect to confirmation page\nonly saved credit card TokenID will be added to query string
website->api: //[[TransactionsApi.md#create-billing-deal create Billing Deal]]// record using CreditCardTokenID and ConsumerID
website->website: store Billing Deal details
website->consumer: payment completed 
@enduml